### ISSUE TITLE
關於在Windows上的安裝使用問題

### ISSUE THREAD

**Issue by mcthesw** [sdadonkey/rime-english#11]
感謝您的付出

我使用的是Windows的Rime Weasel 0.14.3.148，在安裝此方案後無法使用，具體表現為F4出現方案，但是選擇後無法按照demo圖中的樣子顯示使用，並且在朙月拼音中按shift切換為英文模式也無法使用，我是Rime的新使用者，所以對於自己進行的步驟不是很確定，以下簡述一下我的安裝方法：
打開Rime package installer，輸入rime-english，然後回車
我非常想要使用這個方案，如果我少提供了什麼資訊請告訴我，我會補充
再次感謝您的付出

**Comment by mcthesw** [comment]
已经解决问题了，只需要[librime-lua](https://github.com/hchunhui/librime-lua/tree/master/sample)的文件放到用户目录即可

**Comment by ellaann** [comment]
> 已经解决问题了，只需要[librime-lua](https://github.com/hchunhui/librime-lua/tree/master/sample)的文件放到用户目录即可

你好，我已经在“用户文件夹”存放了你提到的文件，但发现还是没有成功，请问有什么差异吗？
![image](https://github.com/user-attachments/assets/beac4b2a-e791-458b-ba06-752dc3acfffb)
